import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ImpersonationIndicator } from "@/components/auth/ImpersonationIndicator";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark min-h-screen`} //! should set minimum height, not the exact hight !!!!
      >
        {/* added dark mode css class */}
        {children}
        <Toaster position="top-right" closeButton={true} />

        {/* Impersonation Indicator */}
        <ImpersonationIndicator />
      </body>
    </html>
  );
}
